### ISSUE TITLE
new install paths and menus

### ISSUE THREAD

**Issue by joanward** [mkdo/cpd#41]
Hi
I have just done a new install in istcpd.org/tdm/ for our Technical Development unit to do some additional testing, but I am having a couple of issues with it.
1) When I login a superadmin who also has admin rights in the root site I get taken into the purple screen rather than the black extended administrator screen. If l look in the network settings it shows me as Superadmin and if I click on the default/root site and view the users it shows me as an Administrator, but I don't see the full site menu that gives all the access to Settings/Plugins etc. How do I get to the black screen that gives access to everything?
2) If I view the root site (istcpd.org/tdm/) and click on a link in the sidebar links I get the page/post not found error, so the path statement appears to be wrong?

Any advice?
Thanks
Joan

**Comment by mwtsn** [comment]
Hi @joanward 

In order to see the black screen you need elevated privileges. On the user profile there will be a check box that says something like: "Grant this user elevated admin privileges."

You may not be able to view this box on your own profile, however another administrator will be able to check the box for you.

With regards to the wrong path when viewing /tdm, if you try going to Settings > Permalinks and saving the permalinks, this will force the rewrite queries to regenerate, and you should be able to view the links again. Failing this, it could be an issue with the way you have multisite configured.
